apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general
spec:
  template:
    metadata:
    labels:
      owner: karpenter
      workload: homelab
      node-type: cheap-spot
      lifecycle: ephemeral
    spec:
      nodeClassRef:
        name: default

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "c", "m"]

        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3.small
            - t3.medium
            - t3a.small
            - t3a.medium
            - m5a.large

        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["3"]

        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]

  limits:
    cpu: 16

  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 20s