name: GitOps Cert-manager Helm Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - "clusters/dev/system/cert-manager/values.yaml"

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: clusters/dev/system/cert-manager

    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4

      - name: Add cert-manager Helm repo
        run: |
          helm repo add cert-manager https://charts.jetstack.io
          helm repo update

      - name: Pull Chart
        run: |
          helm pull cert-manager/cert-manager --untar

      - name: Helm Lint
        run: |
          helm lint ./cert-manager -f cert-manager/values.yaml